web/router.ex
defmodule MebeWeb.Router do
  use Phoenix.Router

  pipeline :browser do
    plug MebeWeb.RequestStartTimePlug
    plug :accepts, ["html", "xml"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/", MebeWeb do
    pipe_through :browser

    get "/p/:page", PageController, :index
    get "/", PageController, :index
    get "/feed", FeedController, :index

    get "/tag/:tag/p/:page", PageController, :tag
    get "/tag/:tag", PageController, :tag
    get "/tag/:tag/feed", FeedController, :tag

    get "/author/:author/p/:page", PageController, :author
    get "/author/:author", PageController, :author
    get "/author/:author/feed", FeedController, :author

    get "/archive/:year/p/:page", PageController, :year
    get "/archive/:year", PageController, :year
    get "/archive/:year/:month/p/:page", PageController, :month
    get "/archive/:year/:month", PageController, :month

    get "/:year/:month/:day/:slug", PageController, :post
    get "/:slug", PageController, :page
  end
end

web/views/layout_view.ex
defmodule MebeWeb.LayoutView do
  use MebeWeb.Web, :view

  alias MebeWeb.Utils

  @doc """
  Resolve title from the current assigns. Will use the current page's or post's title, if available.
  Otherwise will render default title.
  """
  def title(conn) do
    cond do
      conn.assigns[:post] ->
        conn.assigns[:post].title

      conn.assigns[:page] ->
        conn.assigns[:page].title

      true -> Utils.get_conf :blog_name
    end
  end

  @doc """
  Return the extra HTML defined in the config.
  """
  def extra_html(), do: Utils.get_conf :extra_html

  @doc """
  Return the custom footer HTML defined in the config.
  """
  def custom_footer_html(), do: Utils.get_conf :custom_footer_html

  @doc """
  Calculate time taken for request so far.
  """
  def request_time(conn) do
    MebeWeb.RequestStartTimePlug.calculate_time conn
  end

  def safe_round(val) when is_integer(val), do: val
  def safe_round(val), do: Float.round val
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="<%= @blog_author %>">

    <title><%= title @conn %></title>
    
    <%= if @use_default_style do %>
      <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <% end %>

    <%= if @custom_style_path != nil do %>
      <link rel="stylesheet" href="<%= @custom_style_path %>">
    <% end %>
    
    <%= if @enable_feeds do %>
      <%= if assigns[:page_type] == :tag do %>
        <link href="<%= @absolute_url %><%= feed_path @conn, :tag, @tag %>" rel="alternate" type="application/rss+xml" title="RSS feed for tag <%= @tag %>" />
      <% else %>
        <link href="<%= @absolute_url %><%= feed_path @conn, :index %>" rel="alternate" type="application/rss+xml" title="RSS feed" />
      <% end %>
    <% end %>
  </head>

  <body>
    <div class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="<%= @absolute_url %>" class="navbar-brand">
            <%= @blog_name %>
          </a>
        </div>

        <ul class="nav navbar-nav">

          <%= for menuitem <- @menu do %>
            <li>
              <a href="<%= menuitem.slug %>"><%= menuitem.title %></a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <%= render @view_module, @view_template, assigns %>

      <% footer = custom_footer_html %>
      <%= if footer != nil do %>
        <%= raw footer %>
      <%= else %>
        <div class="footer row">
          <div class="col-xs-12 col-sm-4">
            <p>
              © <%= @blog_author %>
            </p>
          </div>
          <div class="col-xs-12 col-sm-4">
            <p>
              <a href="https://blog.nytsoi.net/mebe">
                Powered by Elixir + Phoenix + Mebe
              </a>
            </p>
          </div>
          <div class="col-xs-12 col-sm-4">
            <p>
              <% {time, unit} = request_time @conn %>
              Rendered in <%= time |> safe_round |> trunc %>&nbsp;<%= unit %>.
            </p>
          </div>
        </div>
      <% end %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/old_hash_redirector.js") %>"></script>

    <%= raw extra_html %>
  </body>
</html>

web/templates/layout/feed.xml.eex
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title><%= title @conn %></title>
    <link><%= @absolute_url %></link>
    <description></description>
    <generator>Mebe</generator>
    <copyright>© <%= @blog_author %></copyright>
    
    <%= render @view_module, @view_template, assigns %>
  </channel>
</rss>